name: Android Build

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true
          fetch-depth: 0

      - name: Pull Git LFS
        run: |
          git lfs install
          git lfs pull

      - name: Build Android
        uses: game-ci/unity-builder@v4
        env:
              UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
              UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
              UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          unityVersion: auto
          targetPlatform: Android

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: AndroidBuild
          path: build
